### PR TITLE
Fix the size one case and provide informative error message in the size zero case.

### LINKED ISSUE #48: Bug in Pow4 kernel
See the tests in https://github.com/dannys4/FFTA.jl/pull/47.

### PR DESCRIPTION
**Pull request by andreasnoack**
Currently, the size one case errors and the size zero case hangs. I've also added more tests. There reveal that there is a bug in the pow4 fft but I will file a separate issue for that.

Closes #48

### CODE REVIEW

**Comment by andreasnoack** [comment]
@dannys4 I found the bug in pow4 kernel and have updated this PR with the fix.

File: src/algos.jl [hunk 1]
```diff
@@ -212,7 +212,7 @@ function fft_pow4!(out::AbstractVector{T}, in::AbstractVector{U}, N::Int, start_
         @muladd k2 = start_out + (k+2*m)*stride_out
         @muladd k3 = start_out + (k+3*m)*stride_out
         y_k0, y_k1, y_k2, y_k3 = out[k0], out[k1], out[k2], out[k3]
-        @muladd out[k0] = (y_k0 + y_k2*wk2) + (y_k1*wk1 + y_k3*wk2)
+        @muladd out[k0] = (y_k0 + y_k2*wk2) + (y_k1*wk1 + y_k3*wk3)
```
Comment (andreasnoack) [inline src/algos.jl:215]: This is the fix of the pow4 kernel

Comment (dannys4) [reply src/algos.jl:215]: good catch
